---
- name: ensure locale.gen
  template:
    src: "locale.gen.j2"
    dest: "{{ locale_locale_gen_conf_file }}"
  register: locale_locale_gen_conf
  become: true

- name: ensure locale
  command: locale-gen
  become: true
  when: locale_locale_gen_conf.changed
